service: AWSSelfLearningCloudWatch-2

provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
  versionFunctions: false
  profile: tw-aws-beach

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - sns:*
        - logs:*
        - cloudwatch:*
      Resource: "*"

package:
  artifact: build/libs/hello-cloud-watch-1.0-SNAPSHOT.jar

functions:
  Lambda2New:
    handler: lambda.Lambda2
    timeout: 900
    reservedConcurrency: 100  #ReservedConcurrentExecutions(AWS)
    events:
      - schedule: cron(0/1 * ? * MON-FRI *) #cron(0/1 * ? * MON-FRI *) cron(0 9 ? * 2#1 *)

resources:
  Resources:
    MetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName:
          !Ref Lambda2NewLogGroup
        FilterPattern: "data is 1.0"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: SITE/TRAFFICTWO
            MetricName: CloudWatchSelfLearningMetricNameTWO


    SendEmailTopicTwo:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SendEmailTopicTwo
        Subscription:
          - Endpoint: jiajie.ma@thoughtworks.com
            Protocol: email

    EventTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: cloudwatch.amazonaws.com
              Action: sns:Publish
              Resource: '*'
        Topics:
          - !Ref SendEmailTopicTwo

    LambdaAlarmTwo:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: Lambda alarm Two
        AlarmName: LambdaCustomAlarmTwo
        AlarmActions:
          - !Ref SendEmailTopicTwo
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 1
        Threshold: 0
        Metrics:
          - Expression: failSizeTwo - 0
            Id: cloudwathcalarmTwo
          - Id: failSizeTwo
            MetricStat:
              Metric:
                MetricName: CloudWatchSelfLearningMetricNameTWO
                Namespace: SITE/TRAFFICTWO
              Period: 60
              Stat: Sum
            ReturnData: False
        TreatMissingData: breaching