service: AWSSelfLearning

provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
  versionFunctions: false
  profile: tw-aws-beach

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - sns:*
        - logs:*
        - cloudwatch:*
      Resource: "*"

package:
  artifact: build/libs/hello-cloud-watch-1.0-SNAPSHOT.jar

functions:
  Lambda1New:
    handler: lambda.Lambda1
    timeout: 900
    reservedConcurrency: 100  #ReservedConcurrentExecutions(AWS)
    events:
      - schedule: cron(0 9 ? * 2#1 *) #cron(0/1 * ? * MON-FRI *) cron(0 9 ? * 2#1 *)

resources:
  Resources:
    SendEmailTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SendEmailTopic
        Subscription:
          - Endpoint: jiajie.ma@thoughtworks.com
            Protocol: email

    EventTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: cloudwatch.amazonaws.com
              Action: sns:Publish
              Resource: '*'
        Topics:
          - !Ref SendEmailTopic

    LambdaAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: Lambda alarm
        AlarmName: LambdaCustomAlarm
        AlarmActions:
          - !Ref SendEmailTopic
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 1
        Threshold: 0
        Period: 60
        MetricName: CloudWatchSelfLearningMetricName
        Namespace: SITE/TRAFFIC
        Statistic: Maximum
        TreatMissingData: notBreaching