service: AWSSelfLearning

provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
  versionFunctions: false
  profile: tw-aws-beach

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - sns:Publish
        - logs:*
      Resource: "*"

package:
  artifact: build/libs/hello-cloud-watch-1.0-SNAPSHOT.jar

functions:


resources:
  Resources:
